version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/node:12-stretch
    working_directory: ~/repo
    environment:
      IMAGE_NAME: brianyingling/users-service
jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Installing Node Modules
          command: |
            npm install
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Create workspace
          command: |
            mkdir -p workspace
      - run:
          name: Archive Docker image
          command: |
            docker save -o ./workspace/image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar
  test:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: ~/repo/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: |
            docker load -i ~/repo/workspace/image.tar
      - run: 
          name: Running tests
          command: |
            docker run $IMAGE_NAME npm run test
  deploy:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: ~/repo/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: |
            docker load -i ~/repo/workspace/image.tar
      - run:
          name: Push Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$TAG
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Deploy Code
          command: ./scripts/ci-deploy.sh

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          context: sensei-kubernetes
      - test:
          requires: 
            - build
      - deploy:
          context: sensei-kubernetes
          requires:
            - test
          filters:
            branches:
              only: master
    
            