apiVersion: apps/v1
kind: Deployment
metadata:
    name: users-service
    namespace: default
    labels:
        app: users-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: users-service
    template:
        metadata:
            labels:
                app: users-service
        spec:
            containers:
                - name: users-service
                  image: brianyingling/users-service:$TAG_VERSION
                  ports:
                    - containerPort: 9002
                      name: http
                  env:
                    - name: AWS_ACCESS_KEY_ID
                      valueFrom:
                        secretKeyRef:
                            name: aws_access_key_id
                            key: aws_access_key_id
                    - name: AWS_SECRET_ACCESS_KEY
                      valueFrom:
                        secretKeyRef:
                            name: aws_secret_access_key
                            key: aws_secret_access_key
      


