apiVersion: apps/v1
kind: Deployment
metadata:
    name: users-service
    namespace: default
    labels:
        app: users-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: users-service
    template:
        metadata:
            labels:
                app: users-service
        spec:
            containers:
                - name: users-service
                  image: brianyingling/users-service:$TAG_VERSION
                  ports:
                    - containerPort: 9002
                      name: http


