apiVersion: v1
kind: Service
metadata:
    name: users-service
    namespace: default
    labels:
        app: users-service
spec:
    type: ClusterIP
    ports:
        - port: 9002
          targetPort: http
          name: http
    selector:
        app: users-service